# This workflow will do a clean installation of node and python dependencies, cache/restore them, build the source code and run tests

name: POS GUI Postman Workflow

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ${{github.workspace}}

    strategy:
      matrix:
        node-version: [14.x]
        python-version: ["3.6.9"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pylint
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Installing packages ...
      run: |
        cd ${{github.workspace}}
        ./script/install_all.sh
        ./src/dagent/script/build_dagent.sh
        ./src/dagent/script/run_dagent.sh
        cd ${{github.workspace}}/src/mtool/api
        pip3 install -r requirements.txt
        pip3 install requests-mock
        cd ..
        ./script/run_mtool.sh
    - name: Running PM Tests ...
      run: |
        cd ${{github.workspace}}/src/mtool/api/test
        newman run Mtool_Sanity_Multi_Array_No_QOS.postman_collection.json -e 'Mtool_Env-Git-server.postman_environment.json'
        
