name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: VM
    strategy:
      matrix:
        python-version: ["3.6.9"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout POS GUI
      uses: actions/checkout@v3
      with:
          path: poseidonos-gui
    - name: Checkout POS
      uses: actions/checkout@v3
      with:
          repository: poseidonos/poseidonos
          ref: refs/heads/main
          path: poseidonos
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build POS
      run: |
        cd poseidonos/script
        ./setup_env.sh
        ./pkgdep.sh
        ./build_ibofos.sh
    - name: grep POS process
      run: |
        ps -aux | grep poseidonos
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Installing packages ...
      run: |
        cd poseidonos-gui
        ./script/install_all.sh
        ./src/dagent/script/build_dagent.sh
        ./src/dagent/script/run_dagent.sh
        cd src/mtool/api
        pip3 install -r requirements.txt
        pip3 install requests-mock
        export PYTHONPATH=$PYTHONPATH:$PWD
        python rest/app.py &
    - name: Running PM Tests ... ....
      run: |
        cd test
        newman run Mtool_Sanity_Multi_Array_No_QOS.postman_collection.json -e 'Mtool_Env-Git-server.postman_environment.json'





